### ISSUE TITLE
Reports are not getting generated

### ISSUE THREAD

**Issue by yugandharc9** [faucetsdn/daq#316] opened 2020-03-21 13:22 UTC
We cloned the project.We are following the Wiki. We manually logged out logged in and used `gnome-session-quit` still I is asking the `sudo` for `bin/setup_dev`. This is the log of generated reports but there are no files in the reports. We tried many times please help.

```
Activating venv
Loading config from local/system.conf into inst/config/system.conf
Starting Sat Mar 21 18:36:25 IST 2020
Clearing previous state...
Running as root...
Activating venv
Loading config from local/system.conf into inst/config/system.conf
Release version 1.0.1
ovsdb-server is running with pid 531
ovs-vswitchd is running with pid 954
Creating mudacl templates...
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :shadowJar

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 12s
2 actionable tasks: 2 executed
Running mudacl regression test...
Writing output files to /home/yugandhar/test_iot/daq/mudacl/out/acl_templates
Writing output files to /home/yugandhar/test_iot/daq/mudacl/out/port_acls
Compare out/acl_templates/ with setup/acl_templates/...
Compare out/port_acls/ with setup/port_acls/...
Activating venv
Loading config from local/system.conf into inst/config/system.conf
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :shadowJar UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 571ms
2 actionable tasks: 2 up-to-date

Executing mudacl generator on mud_files/...
Writing output files to /home/yugandhar/test_iot/daq/inst/acl_templates
inst/acl_templates:
total 40
-rw-r--r-- 1 root root  540 Mar 21 18:36 template_bacnet_acl.yaml
-rw-r--r-- 1 root root  332 Mar 21 18:36 template_bacnet_frdev_acl.yaml
-rw-r--r-- 1 root root  332 Mar 21 18:36 template_bacnet_todev_acl.yaml
-rw-r--r-- 1 root root  768 Mar 21 18:36 template_baseline_acl.yaml
-rw-r--r-- 1 root root 1966 Mar 21 18:36 template_commissioning_acl.yaml
-rw-r--r-- 1 root root 1452 Mar 21 18:36 template_controller_acl.yaml
-rw-r--r-- 1 root root   78 Mar 21 18:36 template_default_acl.yaml
-rw-r--r-- 1 root root 1442 Mar 21 18:36 template_lightbulb_acl.yaml
-rw-r--r-- 1 root root  258 Mar 21 18:36 template_raw_acl.yaml
-rw-r--r-- 1 root root  496 Mar 21 18:36 template_telnet_acl.yaml

inst/port_acls:
total 0
No external switch configured.
Sourcing misc/startup_base.cmd...
DAQ autostart cmd/faux
Activating venv
Loading config from local/system.conf into inst/config/system.conf
Launching faux ...
DAQ autoclean docker kill daq-faux
Removing old interface faux
Adding new interface to 12265...
Done with faux device launch.
Entering virtual python environment...
Using python3 at /home/yugandhar/test_iot/daq/venv/bin/python3
Executing: python3 -u daq/daq.py /home/yugandhar/test_iot/daq/local/system.conf -s
Prepending /home/yugandhar/test_iot/daq/binhack to PATH
processing arg: /home/yugandhar/test_iot/daq/local/system.conf
Reading config from /home/yugandhar/test_iot/daq/local/system.conf
Reading config from misc/system.conf
processing arg: -s
base_conf=misc/module_config.json
dhcp_lease_time=500s
initial_dhcp_lease_time=120s
intf_names=faux
long_dhcp_response_sec=80
run_mode=local
single_shot=True
site_description="Baseline Configuration"
site_path=local/site/
startup_cmds=misc/startup_base.cmd
INFO:daq:pid is 12376
INFO:gcp:No gcp_cred credential specified in config
INFO:config:Loading config from misc/module_config.json
INFO:config:Skipping missing local/site/module_config.json
INFO:topology:No device_specs file specified, skipping...
INFO:runner:Reading test definition file misc/host_tests.conf
INFO:runner:Reading test definition file subset/pentests/build.conf
INFO:runner:Configured with tests ['pass', 'fail', 'ping', 'bacnet', 'mudgee', 'nmap', 'discover']
INFO:network:Activating faucet topology...
INFO:topology:Starting faucet...
INFO:network:Initializing faucitizer...
INFO:network:Creating ovs sec with dpid/port 2/7
INFO:network:Added switch link pri-eth1 <-> sec-eth7
INFO:network:Attaching device interface faux on port 1.
INFO:network:Attaching device interface sec-2 on port 2.
INFO:network:Attaching device interface sec-3 on port 3.
INFO:network:Attaching device interface sec-4 on port 4.
INFO:network:Attaching device interface sec-5 on port 5.
INFO:network:Attaching device interface sec-6 on port 6.
INFO:network:Starting mininet...
INFO:mininet:*** Configuring hosts
INFO:mininet:*** Starting controller
INFO:mininet:controller
INFO:mininet:*** Starting 2 switches
INFO:mininet:pri
INFO:mininet:sec
INFO:mininet:...
INFO:runner:Waiting for system to settle...
INFO:runner:Entering main event loop.
INFO:runner:See docs/troubleshooting.md if this blocks for more than a few minutes.
INFO:runner:System port 7 on dpid 2 is active True
INFO:runner:Port 1 dpid 2 is now active True
INFO:runner:Port 1 dpid 2 learned 9a:02:57:1e:8f:00
INFO:runner:Gateway for device group 9a02571e8f00 not found, initializing base 1...
INFO:gateway:Initializing gateway 9a02571e8f00 as gw01/10
INFO:gateway:Added networking host gw01 on port 10 at 10.20.0.1
INFO:gateway:Added dummy target dummy01 on port 11 at 10.20.0.2
INFO:gateway:Gateway 1 startup capture gw01-eth0 in container's /tmp/gateway.pcap
INFO:dhcp:DHCP monitor gw01 waiting for replies...
INFO:runner:Test ping gw01->dummy01
INFO:runner:Test ping gw01->dummy01
INFO:runner:Test ping dummy01->gw01
INFO:runner:Test ping dummy01->192.168.84.1
INFO:runner:Test ping gw01->dummy01 from 192.168.84.1
INFO:gateway:Attaching target 1 to gateway group 9a02571e8f00
WARNING:host:Creating new device dir: /home/yugandhar/test_iot/daq/local/site/mac_addrs/9a02571e8f00
WARNING:host:Skipping defaults since no device_template found
INFO:config:Skipping missing /home/yugandhar/test_iot/daq/local/site/mac_addrs/9a02571e8f00/module_config.json
INFO:config:Skipping missing /home/yugandhar/test_iot/daq/local/site/mac_addrs/9a02571e8f00/module_config.json
INFO:host:Device config reloaded: True 9a:02:57:1e:8f:00
INFO:config:Writing config to /home/yugandhar/test_iot/daq/local/site/mac_addrs/9a02571e8f00/aux/module_config.json
INFO:host:Host 1 running with enabled tests ['pass', 'fail', 'ping', 'nmap']
INFO:report:Creating report as inst/reports/report_9a02571e8f00_2020-03-21T130738+0000.md
INFO:report:Creating report as inst/reports/report_9a02571e8f00_2020-03-21T130738+0000.pdf
INFO:runner:Target port 1 registered 9a:02:57:1e:8f:00
INFO:host:Target port 1 initializing...
INFO:config:Skipping missing /home/yugandhar/test_iot/daq/local/site/mac_addrs/9a02571e8f00/module_config.json
INFO:network:Creating mirror pair mirror-1 <-> mirror-1-ext at 1001
INFO:host:Target port 1 startup pcap capture
INFO:network:Directing traffic for 9a:02:57:1e:8f:00 on port 1: True
INFO:topology:Waiting 5s for network to settle
INFO:host:Target port 1 waiting for ip as 9a:02:57:1e:8f:00
INFO:host:Target port 1 using normal DHCP mode
ERROR:host:Monitoring timeout for ipaddr after 120s
ERROR:host:Target port 1 monitor error: Timeout expired
INFO:host:Target port 1 monitor scan complete
ERROR:runner:Target port 1 active True exception: Timeout expired
INFO:gateway:Detach target 1 from gateway group 9a02571e8f00
INFO:runner:Retiring target gateway 1, 9a:02:57:1e:8f:00, 9a02571e8f00, 1
INFO:gateway:Terminating gateway 1/9a02571e8f00
INFO:runner:Target port 1 finalize: ['01:ipaddr:TimeoutError'] (Timeout expired)
INFO:runner:Target port 1 cancel 9a:02:57:1e:8f:00 (#1/0).
INFO:network:Directing traffic for 9a:02:57:1e:8f:00 on port 1: False
INFO:topology:Waiting 5s for network to settle
INFO:host:Target port 1 terminate, running unknown, trigger False: _target_set_cancel
INFO:network:Deleting mirror pair mirror-1 <-> mirror-1-ext
WARNING:runner:Suppressing future tests because test done in single shot.
INFO:runner:Remaining target sets: []
INFO:stream:Monitoring 0 fds 
WARNING:runner:No active ports remaining (0 monitors), ending test run.
INFO:runner:Stopping network...
INFO:mininet:*** Stopping 1 controllers
INFO:mininet:controller
INFO:mininet:*** Stopping 1 links
INFO:mininet:.
INFO:mininet:*** Stopping 2 switches
INFO:mininet:pri
INFO:mininet:sec
INFO:mininet:*** Stopping 1 hosts
INFO:mininet:gw01
INFO:mininet:*** Done
INFO:runner:Done with runner.
INFO:daq:DAQ runner returned 0
Cleanup docker kill daq-faux
daq-faux
Done with run, exit 0


```

**Comment by grafnu** [comment] 2020-03-21 13:30
It says that reports are getting generated as `INFO:report:Creating report as inst/reports/report_9a02571e8f00_2020-03-21T130738+0000.md` -- and you saying that that file isn't there?  What does the output of `find inst -name \*.md` show?

**Comment by yugandharc9** [comment] 2020-03-21 13:39
Yes that is the issue there is entry in log but file isn't there . Output of `find inst -name \*.md` is blank

**Comment by grafnu** [comment] 2020-03-21 13:44
What is the output of `pwd; ls -l inst inst/reports` ?

**Comment by yugandharc9** [comment] 2020-03-21 13:46
@grafnu  This is the output 

```
/home/yugandhar/test_iot/daq
inst:
total 96
drwxr-xr-x 2 root      root       4096 Mar 21 19:06 acl_templates
-rw-r--r-- 1 yugandhar yugandhar  8234 Mar 21 19:07 cmdrun.log
drwxr-xr-x 2 yugandhar root       4096 Mar 21 16:43 config
-rw-r--r-- 1 yugandhar root        440 Mar 21 18:31 docker_images.txt
-rw-r--r-- 1 yugandhar root       1800 Mar 21 19:07 dp_port_acls.yaml
-rw-r--r-- 1 root      root         35 Mar 21 19:06 exrun_cleanup.sh
srwxr-xr-x 1 root      root          0 Mar 21 19:06 faucet_event.sock
-rw-r--r-- 1 root      root          0 Mar 21 19:06 faucet_exception.log
-rw-r--r-- 1 root      root      36508 Mar 21 19:07 faucet.log
-rw-r--r-- 1 root      root       3984 Mar 21 19:06 faucet.yaml
drwxr-xr-x 3 yugandhar root       4096 Mar 21 18:36 faux
drwxr-xr-x 3 root      root       4096 Mar 21 19:06 gw01
drwxr-xr-x 2 root      root       4096 Mar 21 19:06 port_acls
drwxr-xr-x 2 root      root       4096 Mar 21 19:07 reports
-rw-r--r-- 1 yugandhar root         31 Mar 21 19:07 result.log
drwxr-xr-x 3 root      root       4096 Mar 21 19:07 run-port-01

inst/reports:
total 0

```

**Comment by grafnu** [comment] 2020-03-21 13:49
Hmmm -- ok -- I'm working on reproducing. How did you do the original run, what was the exact commant?  Something like `cmd/run -s`?

**Comment by yugandharc9** [comment] 2020-03-21 13:52
Thank you. Yes it was exactly `cmd/run -s`  I ll keep looking too.

**Comment by grafnu** [comment] 2020-03-21 13:53
This is where it's going wrong, although I don't know why yet. When I run it that part works ok -- the INFO line is ok, but the ERROR is not.
```
INFO:host:Target port 1 using normal DHCP mode
ERROR:host:Monitoring timeout for ipaddr after 120s
ERROR:host:Target port 1 monitor error: Timeout expired
```

**Comment by grafnu** [comment] 2020-03-21 13:54
Can you send along the output of `tcpdump -enr inst/run-port-01/scans/startup.pcap ip` -- that's a pcap of the startup sequence where it should be doing DHCP.

**Comment by yugandharc9** [comment] 2020-03-21 13:55
That is not generated in my case it is giving 

`tcpdump: inst/run-port-01/scans/startup.pcap: No such file or directory
`

**Comment by grafnu** [comment] 2020-03-21 14:00
Huh.  Ok -- when you're running it, at some point it should stop and wait for a bit after the `INFO:host:Target port 1 using normal DHCP mode` line. When that happens, in another window can you try `sudo tcpdump -eni pri-eth1`?  Let that run until `cmd/run -s` exits.

**Comment by grafnu** [comment] 2020-03-21 14:01
Mine looks like this:
```
$ sudo tcpdump -eni pri-eth1
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on pri-eth1, link-type EN10MB (Ethernet), capture size 262144 bytes
06:58:28.927321 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: pri
06:58:28.927393 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: sec
06:58:29.909341 b6:51:24:47:e0:d4 > 33:33:00:00:00:02, ethertype IPv6 (0x86dd), length 70: fe80::b451:24ff:fe47:e0d4 > ff02::2: ICMP6, router solicitation, length 16
06:58:31.957254 2e:ed:df:77:58:f4 > 33:33:00:00:00:02, ethertype IPv6 (0x86dd), length 70: fe80::2ced:dfff:fe77:58f4 > ff02::2: ICMP6, router solicitation, length 16
06:58:35.506983 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: pri
06:58:35.507449 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: sec
06:58:40.793303 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: pri
06:58:40.793526 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: sec
06:58:46.153572 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: pri
06:58:46.153766 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: sec
06:58:48.345749 22:15:32:6a:a0:6c > 33:33:00:00:00:02, ethertype 802.1Q (0x8100), length 74: vlan 10, p 0, ethertype IPv6, fe80::2015:32ff:fe6a:a06c > ff02::2: ICMP6, router solicitation, length 16
06:58:51.364290 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: pri
06:58:51.364532 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: sec
06:58:57.459404 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: pri
06:58:57.459663 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: sec
06:59:02.908700 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: pri
06:59:02.908789 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: sec
06:59:03.777492 9a:02:57:1e:8f:00 > 9e:e1:56:a8:44:bd, ethertype IPv4 (0x0800), length 342: 10.20.61.163.68 > 10.20.0.1.67: BOOTP/DHCP, Request from 9a:02:57:1e:8f:00, length 300
06:59:03.777494 9a:02:57:1e:8f:00 > 9e:e1:56:a8:44:bd, ethertype 802.1Q (0x8100), length 346: vlan 10, p 0, ethertype IPv4, 10.20.61.163.68 > 10.20.0.1.67: BOOTP/DHCP, Request from 9a:02:57:1e:8f:00, length 300
06:59:03.791179 9e:e1:56:a8:44:bd > 9a:02:57:1e:8f:00, ethertype IPv4 (0x0800), length 344: 10.20.0.1.67 > 10.20.61.163.68: BOOTP/DHCP, Reply, length 302
06:59:08.290221 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: pri
06:59:08.290448 0e:00:00:00:00:01 > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 63: LLDP, length 49: sec
06:59:08.821956 9e:e1:56:a8:44:bd > 9a:02:57:1e:8f:00, ethertype ARP (0x0806), length 42: Request who-has 10.20.61.163 tell 10.20.0.1, length 28
06:59:08.822072 9a:02:57:1e:8f:00 > 9e:e1:56:a8:44:bd, ethertype ARP (0x0806), length 42: Request who-has 10.20.0.1 tell 10.20.61.163, length 28
06:59:08.822074 9a:02:57:1e:8f:00 > 9e:e1:56:a8:44:bd, ethertype 802.1Q (0x8100), length 46: vlan 10, p 0, ethertype ARP, Request who-has 10.20.0.1 tell 10.20.61.163, length 28
06:59:08.822485 9a:02:57:1e:8f:00 > 9e:e1:56:a8:44:bd, ethertype ARP (0x0806), length 42: Reply 10.20.61.163 is-at 9a:02:57:1e:8f:00, length 28
06:59:08.822486 9a:02:57:1e:8f:00 > 9e:e1:56:a8:44:bd, ethertype 802.1Q (0x8100), length 46: vlan 10, p 0, ethertype ARP, Reply 10.20.61.163 is-at 9a:02:57:1e:8f:00, length 28
06:59:08.822670 9e:e1:56:a8:44:bd > 9a:02:57:1e:8f:00, ethertype ARP (0x0806), length 42: Reply 10.20.0.1 is-at 9e:e1:56:a8:44:bd, length 28
```

**Comment by grafnu** [comment] 2020-03-21 14:03
Also, while it's waiting for DHCP, try:
```
$ ps ax | fgrep tcpdump
165459 pts/0    Sl     0:00 docker exec --env TERM=dumb -t daq-gw01 tcpdump -i gw01-eth0 -v -Z root -w /tmp/gateway.pcap --immediate-mode -e -n -U
165464 pts/0    Sl     0:00 docker exec --env TERM=dumb -t daq-gw01 tcpdump -i gw01-eth0 -v -Z root --immediate-mode -e -n -U
165514 pts/2    Ss+    0:00 tcpdump -i gw01-eth0 -v -Z root -w /tmp/gateway.pcap --immediate-mode -e -n -U
165543 pts/3    Ss+    0:00 tcpdump -i gw01-eth0 -v -Z root --immediate-mode -e -n -U
165648 ?        Ss     0:00 tcpdump -i mirror-1 -v -Z root -w /home/peringknife/git-clean/inst/run-port-01/scans/startup.pcap --immediate-mode -e -n -U
166435 pts/1    S+     0:00 grep -F --color=auto tcpdump
```

**Comment by yugandharc9** [comment] 2020-03-21 14:05
I do not have ethernet port on my machine I am using wireless interface `tcpdump: pri-eth1: No such device exists
(SIOCGIFHWADDR: No such device)`

Earlier I tried connecting the USB Ethernet adapter and edited the `intf_names` the issue was same .

**Comment by grafnu** [comment] 2020-03-21 14:12
The `pri-eth1` is an internal virtual ethernet link so it doesn't matter about your external connection.  What does the output of `$ sudo ovs-vsctl show` show (while it's waiting for DHCP)?  What's in your `local/system.conf` file?

**Comment by yugandharc9** [comment] 2020-03-21 14:14
I added the  log of `sudo tcpdump -eni pri-eth1` above here is my `local/system.conf`
```
# Base configuration file for DAQ.
#
# This setup will create and test one faux device. To specify a real USB
# adapter, modify the intf_names entry with the appripriate interface name(s).
# The startup_cmds line can then be commented out to prevent the (unnecessary)
# startup of the faux test device.

# Load defaults.
source misc/system.conf

# Description description for dashboard.
site_description="Baseline Configuration"

# CSV separated list of names to assign to external switch interfaces.
intf_names=faux

# Command file with startup commands.
startup_cmds=misc/startup_base.cmd

```

**Comment by grafnu** [comment] 2020-03-21 14:27
Was it waiting for DHCP when you ran `sudo ovs-vsctl show`?  Something is wrong with the capture because there is no way the output would be like it showed. If ovs-vsctl is not showing anything, then the cmd/run would not progress that far.

**Comment by yugandharc9** [comment] 2020-03-21 14:36
No it was not waiting I ll try this on another machine and let you know if this persist.

**Comment by grafnu** [comment] 2020-03-21 15:10
Also the output of this command `timeout 10m docker exec daq-faux tcpdump -eni faux-eth0 ip` -- that will run for 10 minutes (unless there's an error) -- just trying to partition the problem.

**Comment by yugandharc9** [comment] 2020-03-22 08:47
@grafnu 
I tried on another machine I got the same error above for DHCP. May be I am missing something basic, Here are the steps I am following exactly 
```

git clone https://github.com/faucetsdn/faucet.git
bin/setup_base #here asked the sudo
bin/setup_dev # here sudo is asked again I am logging out and logging in ubuntu (not sure what docs expects by logout and logback in)
sudo cmd/build # takes a while
cmd/run -s
```

That's it. Still  getting the 
```
INFO:host:Target port 1 using normal DHCP mode
ERROR:host:Monitoring timeout for ipaddr after 120s
ERROR:host:Target port 1 monitor error: Timeout expired
```
Am I messing up with logout login and sudo?

**Comment by grafnu** [comment] 2020-03-22 12:39
You're cloning the wrong repo and missing a cd.  You also don't need to run
cmd/build as sudo. The logout/login is only required when you install/setup
docker (to handle user group permissions). I don't know which instructions
you're following, exactly -- so if there's some specific bit that's
misleading, please send a pointer. I would expect something like:

git clone https://github.com/faucetsdn/daq.git
cd daq
bin/setup_base
bin/setup_dev
cmd/run -s

**Comment by grafnu** [comment] 2020-03-22 12:41
Also, we primarily use Debian systems, which should be the same as Ubuntu,
but it's possible that something about their network configuration is
causing problems...

**Comment by yugandharc9** [comment] 2020-03-22 13:54
My bad! Typo while logging issue the first google search I am cloning right I will be looking in the network with Debian preferably

**Comment by pisuke** [comment] 2020-04-06 22:47
@yugandharc9 did you have any luck with building the code on a Debian distro?

**Comment by pisuke** [comment] 2020-04-23 16:41
Closing this one as no more discussions or feedback.

**Closed by pisuke** 2020-04-23 16:41 UTC
