### ISSUE TITLE
Scalability problems with many ports

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/daq#70] opened 2019-02-14 15:40 UTC
Works OK with a 6-8 port switch setup, but using a full 48-port switch causes performance problems. Likely related to an O(n^2) algorithm somewhere in Faucet or OVS. Workaround is to keep sec_port set to something small, but eventually this needs to be sorted.

**Comment by grafnu** [comment] 2019-03-14 22:52
This should be fixed as per [an updated faucet version](https://github.com/grafnu/daq/pull/106).  Assigning back to Francesco to figure out how/when to test to validate that it's done.

**Comment by pisuke** [comment] 2019-03-19 14:35
OK, testing it shortly at the 2PS test rig.

**Comment by pisuke** [comment] 2019-03-21 12:12
Tested after git pull, doing a cmd/run -s.
The error below stopped the cmd/run execution.
I fixed it by activating the venv and manually installing the python yaml library.
pip3 install pyyaml
I've pushed [PR #115 ](https://github.com/grafnu/daq/pull/115) on the grafnu fork for this.


Done with local switch setup.
Entering virtual python environment...
Using python3 at /home/tester/grafnu/daq/venv/bin/python3
Executing: python3 -u daq/daq.py /home/tester/grafnu/daq/local/system.conf -s
Prepending /home/tester/grafnu/daq/binhack to PATH
Traceback (most recent call last):
  File "daq/daq.py", line 14, in <module>
    import runner
  File "/home/tester/grafnu/daq/daq/runner.py", line 13, in <module>
    import network
  File "/home/tester/grafnu/daq/daq/network.py", line 6, in <module>
    from topology import FaucetTopology
  File "/home/tester/grafnu/daq/daq/topology.py", line 7, in <module>
    import yaml
ImportError: No module named 'yaml'
Cleanup ip link del ctrl-pri
Cleanup ip link del ctrl-swx
Cleanup ovs-vsctl --if-exists del-br ctrl-br
Done with run, exit 1

**Comment by pisuke** [comment] 2019-03-21 12:41
Done test after fixing the pyyaml dependency and unfortunately it failed.
Here is part of the DAQ command line log

INFO:gateway:Detach target 33 from gateway group 40bd32ebd57c
INFO:runner:Retiring target gateway 33, 40:bd:32:eb:d5:7c, 40bd32ebd57c, 33
INFO:gateway:Terminating gateway 33/40bd32ebd57c
WARNING:runner:Suppressing future tests because test done in single shot.
INFO:runner:Remaining target sets: [1]
INFO:runner:Port 1 dpid 4660 learned 5c:f7:e6:8b:7a:d1
INFO:runner:Port 33 dpid 4660 learned 40:bd:32:eb:d5:7c



INFO:runner:DHCP notify 5c:f7:e6:8b:7a:d1 is 10.20.77.88 on gw01 (long/None/376)
INFO:gateway:Ready target 5c:f7:e6:8b:7a:d1 from gateway group 5cf7e68b7ad1
INFO:runner:DHCP activating target 5c:f7:e6:8b:7a:d1
INFO:host:Target port 1 triggered as 10.20.77.88
INFO:runner:Test ping gw01->10.20.77.88
INFO:runner:Test ping gw01->10.20.77.88
INFO:runner:Test ping gw01->10.20.77.88 from 192.168.84.1
INFO:host:Target port 1 monitor scan complete at 2019-03-21 12:35:52.502440
INFO:host:Target port 1 done with base.
INFO:host:Target port 1 background scan at 2019-03-21 12:35:52.720952 for 30s
ERROR:stream:Monitoring error handling gw01 fd 35: dhcp ACK missing ip address
ERROR:dhcp:DHCP monitor gw01 error: dhcp ACK missing ip address
ERROR:runner:DHCP exception for gw01: dhcp ACK missing ip address
ERROR:runner:dhcp ACK missing ip address
Traceback (most recent call last):
  File "/home/tester/pisuke/daq/daq/stream_monitor.py", line 82, in trigger_callback
    callback()
  File "/home/tester/pisuke/daq/daq/dhcp_monitor.py", line 60, in _dhcp_line
    self._dhcp_success()
  File "/home/tester/pisuke/daq/daq/dhcp_monitor.py", line 76, in _dhcp_success
    assert self.target_ip, 'dhcp ACK missing ip address'
AssertionError: dhcp ACK missing ip address
INFO:runner:Terminating gateway group 5cf7e68b7ad1 set 1, ports [1]
INFO:runner:Target port 1 finalize: [] (gateway set terminating)
INFO:runner:Target port 1 cancel 5c:f7:e6:8b:7a:d1 (#2/0).
INFO:network:Directing traffic for 5c:f7:e6:8b:7a:d1 on port 1: False
INFO:topology:Waiting 5s for network to settle
INFO:host:Target port 1 terminate, trigger False
INFO:host:Target port 1 monitor scan complete at 2019-03-21 12:36:24.791478
INFO:network:Deleting mirror pair mirror-1 <-> mirror-1-ext
INFO:gateway:Detach target 1 from gateway group 5cf7e68b7ad1
INFO:runner:Retiring target gateway 1, 5c:f7:e6:8b:7a:d1, 5cf7e68b7ad1, 1
INFO:gateway:Terminating gateway 1/5cf7e68b7ad1
INFO:runner:Remaining target sets: []
WARNING:runner:No active ports remaining (0): ending test run.
INFO:runner:Stopping network...
INFO:mininet:*** Stopping 1 controllers
INFO:mininet:controller
INFO:mininet:*** Stopping 0 links
INFO:mininet:*** Stopping 1 switches
INFO:mininet:pri
INFO:mininet:*** Stopping 1 hosts
INFO:mininet:gw33
INFO:mininet:*** Done
INFO:runner:Done with runner.
ERROR:runner:Test failures: ['33:nmap:1', '33:ping:1', '33:switch:1']
INFO:daq:DAQ runner returned 1
Cleanup ip link del ctrl-pri
Cleanup ip link del ctrl-swx
Cleanup ovs-vsctl --if-exists del-br ctrl-br
Done with run, exit 1

**Comment by grafnu** [comment] 2019-03-21 13:05
Is that repeatable?  (Does it happen every time?)   Also, if you
reconfigure the system back to 6 max ports, does it still happen?

**Comment by pisuke** [comment] 2019-03-26 12:43
The DHCP ACK error is sporadic, but the failure is repeatable.
Here is the log (please scroll to end for more info)

root@skynet:/home/tester/grafnu/daq# cmd/run -s
Loading config from local/system.conf
Starting Tue 26 Mar 12:29:58 GMT 2019, run_mode is local.
Clearing previous state...
Loading config from local/system.conf
Release version 0.9.5
cleanup_file=inst/exrun_cleanup.sh
ext_addr=192.168.1.2
ext_ctrl=enxb49cdff33ad9
ext_dpid=0x1234
ext_intf=enx645aedf345fa
ext_loip=192.168.1.%d/16
ext_ofip=192.168.1.10/16
ext_ofpt=6653
fail_hook=misc/dump_network.sh
gcp_cred=local/curious-song-211910-eaf1228260dd.json
host_tests=local/local_tests.conf
run_mode=local
sec_port=47
site_description='Bigger Room - DAQ SDN test lab - physical OpenFlow switch'
site_path=local/site/
skip_autostart=
ovsdb-server is running with pid 486
ovs-vswitchd is running with pid 634
Creating mudacl templates...
:compileJava UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:shadowJar UP-TO-DATE

BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 up-to-date
Running mudacl regression test...
Writing output files to /home/tester/grafnu/daq/mudacl/out/acl_templates
Writing output files to /home/tester/grafnu/daq/mudacl/out/port_acls
Compare out/acl_templates/ with setup/acl_templates/...
Compare out/port_acls/ with setup/port_acls/...
Loading config from local/system.conf
:compileJava UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:shadowJar UP-TO-DATE

BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 up-to-date

Executing mudacl generator on mud_files/...
Writing output files to /home/tester/grafnu/daq/inst/acl_templates
inst/acl_templates:
total 40
-rw-r--r-- 1 root root  540 Mar 26 12:30 template_bacnet_acl.yaml
-rw-r--r-- 1 root root  332 Mar 26 12:30 template_bacnet_frdev_acl.yaml
-rw-r--r-- 1 root root  332 Mar 26 12:30 template_bacnet_todev_acl.yaml
-rw-r--r-- 1 root root  768 Mar 26 12:30 template_baseline_acl.yaml
-rw-r--r-- 1 root root 1966 Mar 26 12:30 template_commissioning_acl.yaml
-rw-r--r-- 1 root root 1452 Mar 26 12:30 template_controller_acl.yaml
-rw-r--r-- 1 root root   78 Mar 26 12:30 template_default_acl.yaml
-rw-r--r-- 1 root root 1442 Mar 26 12:30 template_lightbulb_acl.yaml
-rw-r--r-- 1 root root  258 Mar 26 12:30 template_raw_acl.yaml
-rw-r--r-- 1 root root  496 Mar 26 12:30 template_telnet_acl.yaml

inst/port_acls:
total 0
DAQ autostart bin/switch_local
Loading config from local/system.conf
Pulled cplane_mac b4:9c:df:f3:3a:d9 from enxb49cdff33ad9
Cleaning old setup...
Creating ovs-link interfaces...
Creating local-link interfaces...
Creating local bridge...
Configuring ctrl-swy with 192.168.1.10/16
Bridging enxb49cdff33ad9 to ctrl-br
Checking external connection to 192.168.1.2
PING 192.168.1.2 (192.168.1.2) 56(84) bytes of data.
64 bytes from 192.168.1.2: icmp_seq=1 ttl=64 time=4.03 ms
64 bytes from 192.168.1.2: icmp_seq=2 ttl=64 time=0.579 ms

--- 192.168.1.2 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.579/2.305/4.031/1.726 ms
DAQ autoclean ip link del ctrl-pri
DAQ autoclean ip link del ctrl-swx
DAQ autoclean ovs-vsctl --if-exists del-br ctrl-br
Done with local switch setup.
Entering virtual python environment...
Using python3 at /home/tester/grafnu/daq/venv/bin/python3
Executing: python3 -u daq/daq.py /home/tester/grafnu/daq/local/system.conf -s
Prepending /home/tester/grafnu/daq/binhack to PATH
processing arg: /home/tester/grafnu/daq/local/system.conf
Reading config from /home/tester/grafnu/daq/local/system.conf
Reading config from misc/system.conf
processing arg: -s
Configuration map: {'ext_ofpt': '6653', 'ext_ctrl': 'enxb49cdff33ad9', 'ext_ofip': '192.168.1.10/16', 'fail_hook': 'misc/dump_network.sh', 'ext_dpid': '0x1234', 'sec_port': '47', 'gcp_cred': 'local/curious-song-211910-eaf1228260dd.json', 'single_shot': True, 'site_path': 'local/site/', 'ext_loip': '192.168.1.%d/16', 'run_mode': 'local', 'host_tests': 'local/local_tests.conf', 'site_description': 'Bigger Room - DAQ SDN test lab - physical OpenFlow switch', 'ext_intf': 'enx645aedf345fa', 'ext_addr': '192.168.1.2'}
INFO:daq:pid is 26153
INFO:gcp:Loading gcp credentials from local/curious-song-211910-eaf1228260dd.json
INFO:gcp:Initialized gcp pub/sub curious-song-211910:daq-testing-account
INFO:gcp:Initialized gcp firestore curious-song-211910:daq-testing-account
INFO:gcp:Dashboard at https://curious-song-211910.firebaseapp.com/?origin=daq-testing-account
INFO:gcp:Storage bucket curious-song-211910.appspot.com already exists
INFO:runner:Reading test definition file local/local_tests.conf
INFO:runner:Reading test definition file misc/host_tests.conf
INFO:runner:Reading test definition file subset/pentests/build.conf
INFO:runner:Reading test definition file subset/switches/build.conf
INFO:runner:Configured with tests ['pass', 'fail', 'ping', 'nmap', 'brute', 'switch']
INFO:network:Activating faucet topology...
INFO:topology:No device_specs file specified, skipping...
INFO:topology:Writing network config to inst/faucet.yaml
INFO:topology:Starting faucet...
INFO:network:Configuring external secondary with dpid 4660 on intf enx645aedf345fa
INFO:network:Starting mininet...
INFO:mininet:*** Configuring hosts
INFO:mininet:*** Starting controller
INFO:mininet:controller
INFO:mininet:*** Starting 1 switches
INFO:mininet:pri
INFO:mininet:...
INFO:network:Attaching switch interface ctrl-pri on port 1000
INFO:runner:Waiting for system to settle...
INFO:runner:Entering main event loop.
INFO:runner:If this blocks for too long, see docs/test_lab.md for tips and tricks.
INFO:runner:System port 47 on dpid 4660 is active True
INFO:runner:Port 39 dpid 4660 is now active True
INFO:runner:Port 39 dpid 4660 learned 40:bd:32:eb:d5:7c
INFO:runner:Gateway for device group 40bd32ebd57c not found, initializing base 39...
INFO:gateway:Initializing gateway 40bd32ebd57c as gw39/390
INFO:gateway:Added networking host gw39 on port 390 at 10.0.0.1
INFO:gateway:Added dummy target dummy39 on port 391 at 10.0.0.2
INFO:gateway:Gateway 39 startup capture gw39-eth0 in container's /tmp/startup.pcap
INFO:dhcp:DHCP monitor gw39 waiting for replies...
INFO:runner:Test ping gw39->dummy39
INFO:gateway:Gateway gw39 warmup failed at 2019-03-26 12:30:30.528711 with 4
INFO:runner:Test ping gw39->dummy39
INFO:runner:Test ping gw39->dummy39
INFO:runner:Test ping dummy39->gw39
INFO:runner:Test ping dummy39->192.168.84.39
INFO:runner:Test ping gw39->dummy39 from 192.168.84.39
INFO:gateway:Attaching target 39 to gateway group 40bd32ebd57c
INFO:report:Creating report as inst/reports/report_40bd32ebd57c_2019-03-26T123046+0000.txt
INFO:report:Device description local/site/mac_addrs/40bd32ebd57c/report_description.txt not found
INFO:report:Device report path local/site/mac_addrs/40bd32ebd57c not found
INFO:runner:Target port 39 registered 40:bd:32:eb:d5:7c
INFO:host:Target port 39 initializing...
INFO:network:Creating mirror pair mirror-39 <-> mirror-39-ext at 1039
INFO:host:Target port 39 startup pcap capture
INFO:network:Directing traffic for 40:bd:32:eb:d5:7c on port 39: True
INFO:topology:Waiting 5s for network to settle
INFO:host:Target port 39 waiting for dhcp as 40:bd:32:eb:d5:7c
INFO:runner:DHCP notify 40:bd:32:eb:d5:7c is 10.20.51.66 on gw39 (long/None/83)
INFO:gateway:Ready target 40:bd:32:eb:d5:7c from gateway group 40bd32ebd57c
INFO:runner:DHCP activating target 40:bd:32:eb:d5:7c
INFO:host:Target port 39 triggered as 10.20.51.66
INFO:runner:Test ping gw39->10.20.51.66
INFO:runner:Test ping gw39->10.20.51.66
INFO:runner:Test ping gw39->10.20.51.66 from 192.168.84.39
INFO:host:Target port 39 monitor scan complete at 2019-03-26 12:32:04.929010
INFO:host:Target port 39 done with base.
INFO:host:Target port 39 background scan at 2019-03-26 12:32:05.052360 for 30s
INFO:host:Target port 39 scan complete
INFO:host:Target port 39 monitor scan complete at 2019-03-26 12:32:35.105712
INFO:docker:Target port 39 test pass running
INFO:docker:Target port 39 test pass passed 1.270769s
INFO:docker:Target port 39 test fail running
INFO:docker:Target port 39 test fail failed 1.29585s: 1 None
WARNING:host:Executing fail_hook: misc/dump_network.sh inst/fail_fail39
ovs-ofctl: ext-ovs is not a bridge or a socket
ovs-ofctl: ext-ovs is not a bridge or a socket
INFO:docker:Target port 39 test ping running
INFO:docker:Target port 39 test ping failed 1.301265s: 1 None
WARNING:host:Executing fail_hook: misc/dump_network.sh inst/fail_ping39
ovs-ofctl: ext-ovs is not a bridge or a socket
ovs-ofctl: ext-ovs is not a bridge or a socket
INFO:docker:Target port 39 test nmap running
INFO:docker:Target port 39 test nmap failed 8.750988s: 1 None
WARNING:host:Executing fail_hook: misc/dump_network.sh inst/fail_nmap39
ovs-ofctl: ext-ovs is not a bridge or a socket
ovs-ofctl: ext-ovs is not a bridge or a socket
INFO:docker:Target port 39 test brute running
INFO:docker:Target port 39 test brute passed 6.355325s
INFO:docker:Target port 39 test switch running
INFO:runner:DHCP notify 40:bd:32:eb:d5:7c is 10.20.51.66 on gw39 (None/None/65)
INFO:runner:DHCP activation group 40bd32ebd57c already activated
INFO:docker:Target port 39 test switch failed 1.340208s: 1 None
WARNING:host:Executing fail_hook: misc/dump_network.sh inst/fail_switch39
ovs-ofctl: ext-ovs is not a bridge or a socket
ovs-ofctl: ext-ovs is not a bridge or a socket
INFO:host:Target port 39 no more tests remaining
INFO:report:Finalizing report report_40bd32ebd57c_2019-03-26T123046+0000.txt
INFO:report:Copying test report inst/run-port-39/nodes/ping39/tmp/report.txt
INFO:report:Copying test report inst/run-port-39/nodes/nmap39/tmp/report.txt
INFO:report:Copying test report inst/run-port-39/nodes/brute39/tmp/report.txt
INFO:gcp:Uploaded test report to inst/reports/report_40bd32ebd57c_2019-03-26T123046+0000.txt
INFO:runner:Target port 39 finalize: ['39:nmap:1', '39:ping:1', '39:switch:1'] (target set not active)
INFO:runner:Target port 39 cancel 40:bd:32:eb:d5:7c (#1/0).
INFO:network:Directing traffic for 40:bd:32:eb:d5:7c on port 39: False
INFO:topology:Waiting 5s for network to settle
INFO:host:Target port 39 terminate, trigger False
INFO:network:Deleting mirror pair mirror-39 <-> mirror-39-ext
INFO:gateway:Detach target 39 from gateway group 40bd32ebd57c
INFO:runner:Retiring target gateway 39, 40:bd:32:eb:d5:7c, 40bd32ebd57c, 39
INFO:gateway:Terminating gateway 39/40bd32ebd57c
WARNING:runner:Suppressing future tests because test done in single shot.
INFO:runner:Remaining target sets: []
WARNING:runner:No active ports remaining (0): ending test run.
INFO:runner:Stopping network...
INFO:mininet:*** Stopping 1 controllers
INFO:mininet:controller
INFO:mininet:*** Stopping 0 links
INFO:mininet:*** Stopping 1 switches
INFO:mininet:pri
INFO:mininet:*** Stopping 1 hosts
INFO:mininet:gw39
INFO:mininet:*** Done
INFO:runner:Done with runner.
ERROR:runner:Test failures: ['39:nmap:1', '39:ping:1', '39:switch:1']
INFO:daq:DAQ runner returned 1
Cleanup ip link del ctrl-pri
Cleanup ip link del ctrl-swx
Cleanup ovs-vsctl --if-exists del-br ctrl-br
Done with run, exit 1

cat inst/run-port-39/nodes/ping39/activate.log
...

reading from file /scans/startup.pcap, link-type EN10MB (Ethernet)
	    DHCP-Message Option 53, length 1: Request

reading from file /scans/startup.pcap, link-type EN10MB (Ethernet)
	    DHCP-Message Option 53, length 1: ACK

Configuring network with local address 192.168.1.392/16.
Error: any valid prefix is expected rather than "192.168.1.392/16".

So it looks like the "lazy math" is still there.

For reference, I've done a git pull from grafnu/daq

Putting the device to a port lower than 6:

....
ERROR:runner:Test failures: ['03:nmap:1', '03:switch:1']
INFO:daq:DAQ runner returned 1
Cleanup ip link del ctrl-pri
Cleanup ip link del ctrl-swx
Cleanup ovs-vsctl --if-exists del-br ctrl-br
Done with run, exit 1

cat inst/run-port-03/nodes/ping03/activate.log


reading from file /scans/startup.pcap, link-type EN10MB (Ethernet)
	    DHCP-Message Option 53, length 1: Request

reading from file /scans/startup.pcap, link-type EN10MB (Ethernet)
	    DHCP-Message Option 53, length 1: ACK

Configuring network with local address 192.168.1.32/16.
Switch test with port 3.
PING 192.168.1.2 (192.168.1.2) 56(84) bytes of data.
From 192.168.1.32 icmp_seq=1 Destination Host Unreachable
From 192.168.1.32 icmp_seq=2 Destination Host Unreachable
From 192.168.1.32 icmp_seq=3 Destination Host Unreachable
64 bytes from 192.168.1.2: icmp_seq=5 ttl=64 time=8.98 ms
64 bytes from 192.168.1.2: icmp_seq=4 ttl=64 time=1033 ms
64 bytes from 192.168.1.2: icmp_seq=6 ttl=64 time=1.84 ms
64 bytes from 192.168.1.2: icmp_seq=7 ttl=64 time=0.763 ms
64 bytes from 192.168.1.2: icmp_seq=8 ttl=64 time=0.743 ms
64 bytes from 192.168.1.2: icmp_seq=9 ttl=64 time=0.608 ms
64 bytes from 192.168.1.2: icmp_seq=10 ttl=64 time=0.816 ms

--- 192.168.1.2 ping statistics ---
10 packets transmitted, 7 received, +3 errors, 30% packet loss, time 9138ms
rtt min/avg/max/mdev = 0.608/149.571/1033.231/360.763 ms, pipe 4
/config/ping_runtime.sh not found.
PING 10.20.24.66 (10.20.24.66) 56(84) bytes of data.
64 bytes from 10.20.24.66: icmp_seq=1 ttl=64 time=10.5 ms
64 bytes from 10.20.24.66: icmp_seq=2 ttl=64 time=1.31 ms
64 bytes from 10.20.24.66: icmp_seq=3 ttl=64 time=1.56 ms
64 bytes from 10.20.24.66: icmp_seq=4 ttl=64 time=1.58 ms
64 bytes from 10.20.24.66: icmp_seq=5 ttl=64 time=1.63 ms
64 bytes from 10.20.24.66: icmp_seq=6 ttl=64 time=2.92 ms
64 bytes from 10.20.24.66: icmp_seq=7 ttl=64 time=1.64 ms
64 bytes from 10.20.24.66: icmp_seq=8 ttl=64 time=1.65 ms
64 bytes from 10.20.24.66: icmp_seq=9 ttl=64 time=1.51 ms
64 bytes from 10.20.24.66: icmp_seq=10 ttl=64 time=1.45 ms

--- 10.20.24.66 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9015ms
rtt min/avg/max/mdev = 1.313/2.587/10.585/2.699 ms

Done with basic connectivity tests.

cat inst/run-port-03/nodes/switch03/activate.log

Configuring network with local address 192.168.1.32/16.
Switch test with port 3.
PING 192.168.1.2 (192.168.1.2) 56(84) bytes of data.
64 bytes from 192.168.1.2: icmp_seq=6 ttl=64 time=1.02 ms
64 bytes from 192.168.1.2: icmp_seq=7 ttl=64 time=0.734 ms
64 bytes from 192.168.1.2: icmp_seq=8 ttl=64 time=0.772 ms
64 bytes from 192.168.1.2: icmp_seq=9 ttl=64 time=0.828 ms
64 bytes from 192.168.1.2: icmp_seq=10 ttl=64 time=0.665 ms

--- 192.168.1.2 ping statistics ---
10 packets transmitted, 5 received, 50% packet loss, time 9150ms
rtt min/avg/max/mdev = 0.665/0.805/1.026/0.122 ms
Exception in thread "main" java.lang.IllegalArgumentException: Expected ipAddress && port as argument
	at switchtest.Main.main(Main.java:8)

Let me know if you need more tests and if I've done all the useful checks.

**Comment by grafnu** [comment] 2019-03-26 12:56
Sigh -- I forgot about that.  I filed https://github.com/faucetsdn/daq/issues/114 for that issue, since it's a bit different. 

Can you try with a max port of 24?

(Also, for lots of log files it's probably better to attach them rather than include them inline -- after a while the UI gets hard to use with long log listings!)

**Comment by pisuke** [comment] 2019-06-11 17:37
Now tried with max port of 24 and it works fine. 
The problem persists with ports higher than 24.
Closing this issue now.

**Closed by pisuke** 2019-06-11 17:37 UTC
Labels: bug
